name: midterm_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.2
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  web_socket_channel: ^2.1.0
  http: ^0.13.3
  firebase_core: "^1.7.0"
  cloud_firestore: "^2.5.3"
  firebase_auth: "^3.2.0"


dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - 'assets/angry.png'
    - 'assets/appicon.PNG'
    - 'assets/beer.png'
    - 'assets/broken.png'
    - 'assets/cinema.png'
    - 'assets/cloud.png'
    - 'assets/cutlery.png'
    - 'assets/DailyActivities.png'
    - 'assets/DailyMood.png'
    - 'assets/DailyQuote.png'
    - 'assets/date.png'
    - 'assets/digisticker.PNG'
    - 'assets/escape.png'
    - 'assets/excited.png'
    - 'assets/exercise.png'
    - 'assets/face.png'
    - 'assets/family.png'
    - 'assets/gaming.png'
    - 'assets/giftbox.png'
    - 'assets/guitar.png'
    - 'assets/happy.png'
    - 'assets/headphones.png'
    - 'assets/home.png'
    - 'assets/hospital.png'
    - 'assets/laugh.png'
    - 'assets/letter.png'
    - 'assets/LogIn.png'
    - 'assets/love.png'
    - 'assets/medicine.png'
    - 'assets/memo.PNG'
    - 'assets/notebook.PNG'
    - 'assets/overtime.png'
    - 'assets/paint.png'
    - 'assets/park.png'
    - 'assets/party.png'
    - 'assets/payment.jpg'
    - 'assets/picnic.png'
    - 'assets/presents.png'
    - 'assets/rain.png'
    - 'assets/reading.png'
    - 'assets/sad.png'
    - 'assets/sick.png'
    - 'assets/sneakers.png'
    - 'assets/snowflake.png'
    - 'assets/stethoscope.png'
    - 'assets/Store.png'
    - 'assets/suitcase.png'
    - 'assets/sun.png'
    - 'assets/TaskOverview.png'
    - 'assets/tv.png'
    - 'assets/User.png'
    - 'assets/van.png'
    - 'assets/wind.png'
    - 'assets/icon.png'
    - 'assets/userpic.png'
